org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get the right Forge MDK
minecraft_version=1.21.1

# The Minecraft version range can use any version of Minecraft as a valid range
minecraft_version_range=[1.21.1,1.21.2)

# The Forge version must agree with the Minecraft version to get a compatible product
forge_version=52.0.53

# The Forge version range can use any version of Forge as a valid range
forge_version_range=[52.0,)

# The loader version range can use any version of Forge as a valid range
loader_version_range=[52.0,)

# The mapping channel to use for the mappings.
# The official (Mojang) mappings are used by default.
mapping_channel=official
mapping_version=1.21.1

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the RFC 1123 naming convention
mod_id=nucleareclipse

# The human-readable display name for the mod
mod_name=Nuclear Eclipse

# The license of the mod. Should be an SPDX identifier
mod_license=MIT

# The mod version. See https://semver.org/
mod_version=1.0.0

# The group ID for the mod
mod_group_id=com.nucleareclipse

# The authors of the mod
mod_authors=Aymen

# The description of the mod
mod_description=A legendary Minecraft mod adding 7 unique, never-before-seen nuclear bombs with mind-bending effects, custom particles, and gorgeous textures.
